### PR TITLE
ci: update matrix to include multiple Julia versions

### PR DESCRIPTION
**Pull request by cpaniaguam**
- checks for both ubuntu (x64) and macos (arm64)
- Julia versions  ['1.9', '1.10', '~1.11.0-0']

### CODE REVIEW

**Review by hollandjg — APPROVED** [review]
Looks good to me!

Just a question: does something fail on Ubuntu Arm64? I guess people will be moving more and more to ARM for all OSes, and it'd be interesting to know whether this can be compatible.

**Comment by cpaniaguam** [comment]
> Just a question: does something fail on Ubuntu Arm64? I guess people will be moving more and more to ARM for all OSes, and it'd be interesting to know whether this can be compatible.

I 

See the failed jobs at github.com/WilhelmusLab/IceFloeTracker.jl/actions/runs/11057508568/job/30721473127. Had to remove the (ubuntu, arm64) combinations.

**Comment by cpaniaguam** [comment]
> Just a question: does something fail on Ubuntu Arm64? I guess people will be moving more and more to ARM for all OSes, and it'd be interesting to know whether this can be compatible.

See the failed jobs from this ci run[this ci run](https://github.com/WilhelmusLab/IceFloeTracker.jl/actions/runs/11057508568/job/30721473127#step:6:37) . Had to remove the (ubuntu, arm64) combinations.

**Comment by cpaniaguam** [comment]
> Just a question: does something fail on Ubuntu Arm64? I guess people will be moving more and more to ARM for all OSes, and it'd be interesting to know whether this can be compatible.

See the failed jobs from this ci [run](https://github.com/WilhelmusLab/IceFloeTracker.jl/actions/runs/11057508568/job/30721473127#step:6:37) . Had to remove the (ubuntu, arm64) combinations.

**Pull request merged**
